### ISSUE TITLE
bug: Type error from parser run services

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/fourkeys#337]
Parser run services are experiencing an error when receiving events:
`
2022-07-13T01:57:27.126156ZTraceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker worker.init_process() File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process super(ThreadWorker, self).init_process() File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process self.load_wsgi() File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi self.wsgi = self.app.wsgi() File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load return self.load_wsgiapp() File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp return util.import_app(self.app_uri) File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app __import__(module) File "/app/main.py", line 19, in <module> import shared File "/usr/local/lib/python3.7/site-packages/shared.py", line 17, in <module> from google.cloud import bigquery File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module> from google.cloud.bigquery.client import Client File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 58, in <module> from google.cloud.bigquery import _pandas_helpers File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 40, in <module> from google.cloud.bigquery import schema File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/schema.py", line 19, in <module> from google.cloud.bigquery_v2 import types File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery_v2/__init__.py", line 23, in <module> from google.cloud.bigquery_v2 import types File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery_v2/types.py", line 23, in <module> from google.cloud.bigquery_v2.proto import encryption_config_pb2 File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery_v2/proto/encryption_config_pb2.py", line 64, in <module> file=DESCRIPTOR, File "/usr/local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__ _message.Message._CheckCalledFromGeneratedFile() TypeError: Descriptors cannot not be created directly.
`

Full log:
[runlogs.txt](https://github.com/GoogleCloudPlatform/fourkeys/files/9098821/runlogs.txt)

**Comment by dinagraves** [comment]
Looks like it's a problem with the underlying protocol buffers:  https://github.com/protocolbuffers/protobuf/issues/10051

Looking at the logs, it looks like it's a problem with the bigquery import.

**Comment by dinagraves** [comment]
Maybe try bumping the version on all the libraries and see if that helps?  The one we're using is quite old.  bq-workers/github-parser/requirements.txt
